development:
   adapter: mysql2
   database: demo_rails_development
   username: root
   password: ""
   host: localhost
test:
   adapter: mysql2
   database: demo_rails_test
   username: root
   password: ""
   host: localhost
production:
   adapter: mysql2
   database: demo_rails_production
   username: root
   password: ""
   host: localhost